// Code generated by BobGen psql v0.0.4-0.20260105020634-53e08d840e47+dirty. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Districts                          districtWhere[Q]
	FieldseekerContainerrelates        fieldseekerContainerrelateWhere[Q]
	FieldseekerFieldscoutinglogs       fieldseekerFieldscoutinglogWhere[Q]
	FieldseekerHabitatrelates          fieldseekerHabitatrelateWhere[Q]
	FieldseekerInspectionsamples       fieldseekerInspectionsampleWhere[Q]
	FieldseekerInspectionsampledetails fieldseekerInspectionsampledetailWhere[Q]
	FieldseekerLinelocations           fieldseekerLinelocationWhere[Q]
	FieldseekerLocationtrackings       fieldseekerLocationtrackingWhere[Q]
	FieldseekerMosquitoinspections     fieldseekerMosquitoinspectionWhere[Q]
	FieldseekerPointlocations          fieldseekerPointlocationWhere[Q]
	FieldseekerPolygonlocations        fieldseekerPolygonlocationWhere[Q]
	FieldseekerPools                   fieldseekerPoolWhere[Q]
	FieldseekerPooldetails             fieldseekerPooldetailWhere[Q]
	FieldseekerProposedtreatmentareas  fieldseekerProposedtreatmentareaWhere[Q]
	FieldseekerQamosquitoinspections   fieldseekerQamosquitoinspectionWhere[Q]
	FieldseekerRodentlocations         fieldseekerRodentlocationWhere[Q]
	FieldseekerSamplecollections       fieldseekerSamplecollectionWhere[Q]
	FieldseekerSamplelocations         fieldseekerSamplelocationWhere[Q]
	FieldseekerServicerequests         fieldseekerServicerequestWhere[Q]
	FieldseekerSpeciesabundances       fieldseekerSpeciesabundanceWhere[Q]
	FieldseekerStormdrains             fieldseekerStormdrainWhere[Q]
	FieldseekerTimecards               fieldseekerTimecardWhere[Q]
	FieldseekerTrapdata                fieldseekerTrapdatumWhere[Q]
	FieldseekerTraplocations           fieldseekerTraplocationWhere[Q]
	FieldseekerTreatments              fieldseekerTreatmentWhere[Q]
	FieldseekerTreatmentareas          fieldseekerTreatmentareaWhere[Q]
	FieldseekerZones                   fieldseekerZoneWhere[Q]
	FieldseekerZones2s                 fieldseekerZones2Where[Q]
	FieldseekerSyncs                   fieldseekerSyncWhere[Q]
	GeographyColumns                   geographyColumnWhere[Q]
	GeometryColumns                    geometryColumnWhere[Q]
	GooseDBVersions                    gooseDBVersionWhere[Q]
	H3Aggregations                     h3AggregationWhere[Q]
	NoteAudios                         noteAudioWhere[Q]
	NoteAudioBreadcrumbs               noteAudioBreadcrumbWhere[Q]
	NoteAudioData                      noteAudioDatumWhere[Q]
	NoteImages                         noteImageWhere[Q]
	NoteImageBreadcrumbs               noteImageBreadcrumbWhere[Q]
	NoteImageData                      noteImageDatumWhere[Q]
	Notifications                      notificationWhere[Q]
	OauthTokens                        oauthTokenWhere[Q]
	Organizations                      organizationWhere[Q]
	PublicreportNuisances              publicreportNuisanceWhere[Q]
	PublicreportPools                  publicreportPoolWhere[Q]
	PublicreportPoolPhotos             publicreportPoolPhotoWhere[Q]
	PublicreportQuicks                 publicreportQuickWhere[Q]
	PublicreportQuickPhotos            publicreportQuickPhotoWhere[Q]
	PublicreportReportLocations        publicreportReportLocationWhere[Q]
	RasterColumns                      rasterColumnWhere[Q]
	RasterOverviews                    rasterOverviewWhere[Q]
	Sessions                           sessionWhere[Q]
	SpatialRefSys                      spatialRefSyWhere[Q]
	Users                              userWhere[Q]
} {
	return struct {
		Districts                          districtWhere[Q]
		FieldseekerContainerrelates        fieldseekerContainerrelateWhere[Q]
		FieldseekerFieldscoutinglogs       fieldseekerFieldscoutinglogWhere[Q]
		FieldseekerHabitatrelates          fieldseekerHabitatrelateWhere[Q]
		FieldseekerInspectionsamples       fieldseekerInspectionsampleWhere[Q]
		FieldseekerInspectionsampledetails fieldseekerInspectionsampledetailWhere[Q]
		FieldseekerLinelocations           fieldseekerLinelocationWhere[Q]
		FieldseekerLocationtrackings       fieldseekerLocationtrackingWhere[Q]
		FieldseekerMosquitoinspections     fieldseekerMosquitoinspectionWhere[Q]
		FieldseekerPointlocations          fieldseekerPointlocationWhere[Q]
		FieldseekerPolygonlocations        fieldseekerPolygonlocationWhere[Q]
		FieldseekerPools                   fieldseekerPoolWhere[Q]
		FieldseekerPooldetails             fieldseekerPooldetailWhere[Q]
		FieldseekerProposedtreatmentareas  fieldseekerProposedtreatmentareaWhere[Q]
		FieldseekerQamosquitoinspections   fieldseekerQamosquitoinspectionWhere[Q]
		FieldseekerRodentlocations         fieldseekerRodentlocationWhere[Q]
		FieldseekerSamplecollections       fieldseekerSamplecollectionWhere[Q]
		FieldseekerSamplelocations         fieldseekerSamplelocationWhere[Q]
		FieldseekerServicerequests         fieldseekerServicerequestWhere[Q]
		FieldseekerSpeciesabundances       fieldseekerSpeciesabundanceWhere[Q]
		FieldseekerStormdrains             fieldseekerStormdrainWhere[Q]
		FieldseekerTimecards               fieldseekerTimecardWhere[Q]
		FieldseekerTrapdata                fieldseekerTrapdatumWhere[Q]
		FieldseekerTraplocations           fieldseekerTraplocationWhere[Q]
		FieldseekerTreatments              fieldseekerTreatmentWhere[Q]
		FieldseekerTreatmentareas          fieldseekerTreatmentareaWhere[Q]
		FieldseekerZones                   fieldseekerZoneWhere[Q]
		FieldseekerZones2s                 fieldseekerZones2Where[Q]
		FieldseekerSyncs                   fieldseekerSyncWhere[Q]
		GeographyColumns                   geographyColumnWhere[Q]
		GeometryColumns                    geometryColumnWhere[Q]
		GooseDBVersions                    gooseDBVersionWhere[Q]
		H3Aggregations                     h3AggregationWhere[Q]
		NoteAudios                         noteAudioWhere[Q]
		NoteAudioBreadcrumbs               noteAudioBreadcrumbWhere[Q]
		NoteAudioData                      noteAudioDatumWhere[Q]
		NoteImages                         noteImageWhere[Q]
		NoteImageBreadcrumbs               noteImageBreadcrumbWhere[Q]
		NoteImageData                      noteImageDatumWhere[Q]
		Notifications                      notificationWhere[Q]
		OauthTokens                        oauthTokenWhere[Q]
		Organizations                      organizationWhere[Q]
		PublicreportNuisances              publicreportNuisanceWhere[Q]
		PublicreportPools                  publicreportPoolWhere[Q]
		PublicreportPoolPhotos             publicreportPoolPhotoWhere[Q]
		PublicreportQuicks                 publicreportQuickWhere[Q]
		PublicreportQuickPhotos            publicreportQuickPhotoWhere[Q]
		PublicreportReportLocations        publicreportReportLocationWhere[Q]
		RasterColumns                      rasterColumnWhere[Q]
		RasterOverviews                    rasterOverviewWhere[Q]
		Sessions                           sessionWhere[Q]
		SpatialRefSys                      spatialRefSyWhere[Q]
		Users                              userWhere[Q]
	}{
		Districts:                          buildDistrictWhere[Q](Districts.Columns),
		FieldseekerContainerrelates:        buildFieldseekerContainerrelateWhere[Q](FieldseekerContainerrelates.Columns),
		FieldseekerFieldscoutinglogs:       buildFieldseekerFieldscoutinglogWhere[Q](FieldseekerFieldscoutinglogs.Columns),
		FieldseekerHabitatrelates:          buildFieldseekerHabitatrelateWhere[Q](FieldseekerHabitatrelates.Columns),
		FieldseekerInspectionsamples:       buildFieldseekerInspectionsampleWhere[Q](FieldseekerInspectionsamples.Columns),
		FieldseekerInspectionsampledetails: buildFieldseekerInspectionsampledetailWhere[Q](FieldseekerInspectionsampledetails.Columns),
		FieldseekerLinelocations:           buildFieldseekerLinelocationWhere[Q](FieldseekerLinelocations.Columns),
		FieldseekerLocationtrackings:       buildFieldseekerLocationtrackingWhere[Q](FieldseekerLocationtrackings.Columns),
		FieldseekerMosquitoinspections:     buildFieldseekerMosquitoinspectionWhere[Q](FieldseekerMosquitoinspections.Columns),
		FieldseekerPointlocations:          buildFieldseekerPointlocationWhere[Q](FieldseekerPointlocations.Columns),
		FieldseekerPolygonlocations:        buildFieldseekerPolygonlocationWhere[Q](FieldseekerPolygonlocations.Columns),
		FieldseekerPools:                   buildFieldseekerPoolWhere[Q](FieldseekerPools.Columns),
		FieldseekerPooldetails:             buildFieldseekerPooldetailWhere[Q](FieldseekerPooldetails.Columns),
		FieldseekerProposedtreatmentareas:  buildFieldseekerProposedtreatmentareaWhere[Q](FieldseekerProposedtreatmentareas.Columns),
		FieldseekerQamosquitoinspections:   buildFieldseekerQamosquitoinspectionWhere[Q](FieldseekerQamosquitoinspections.Columns),
		FieldseekerRodentlocations:         buildFieldseekerRodentlocationWhere[Q](FieldseekerRodentlocations.Columns),
		FieldseekerSamplecollections:       buildFieldseekerSamplecollectionWhere[Q](FieldseekerSamplecollections.Columns),
		FieldseekerSamplelocations:         buildFieldseekerSamplelocationWhere[Q](FieldseekerSamplelocations.Columns),
		FieldseekerServicerequests:         buildFieldseekerServicerequestWhere[Q](FieldseekerServicerequests.Columns),
		FieldseekerSpeciesabundances:       buildFieldseekerSpeciesabundanceWhere[Q](FieldseekerSpeciesabundances.Columns),
		FieldseekerStormdrains:             buildFieldseekerStormdrainWhere[Q](FieldseekerStormdrains.Columns),
		FieldseekerTimecards:               buildFieldseekerTimecardWhere[Q](FieldseekerTimecards.Columns),
		FieldseekerTrapdata:                buildFieldseekerTrapdatumWhere[Q](FieldseekerTrapdata.Columns),
		FieldseekerTraplocations:           buildFieldseekerTraplocationWhere[Q](FieldseekerTraplocations.Columns),
		FieldseekerTreatments:              buildFieldseekerTreatmentWhere[Q](FieldseekerTreatments.Columns),
		FieldseekerTreatmentareas:          buildFieldseekerTreatmentareaWhere[Q](FieldseekerTreatmentareas.Columns),
		FieldseekerZones:                   buildFieldseekerZoneWhere[Q](FieldseekerZones.Columns),
		FieldseekerZones2s:                 buildFieldseekerZones2Where[Q](FieldseekerZones2s.Columns),
		FieldseekerSyncs:                   buildFieldseekerSyncWhere[Q](FieldseekerSyncs.Columns),
		GeographyColumns:                   buildGeographyColumnWhere[Q](GeographyColumns.Columns),
		GeometryColumns:                    buildGeometryColumnWhere[Q](GeometryColumns.Columns),
		GooseDBVersions:                    buildGooseDBVersionWhere[Q](GooseDBVersions.Columns),
		H3Aggregations:                     buildH3AggregationWhere[Q](H3Aggregations.Columns),
		NoteAudios:                         buildNoteAudioWhere[Q](NoteAudios.Columns),
		NoteAudioBreadcrumbs:               buildNoteAudioBreadcrumbWhere[Q](NoteAudioBreadcrumbs.Columns),
		NoteAudioData:                      buildNoteAudioDatumWhere[Q](NoteAudioData.Columns),
		NoteImages:                         buildNoteImageWhere[Q](NoteImages.Columns),
		NoteImageBreadcrumbs:               buildNoteImageBreadcrumbWhere[Q](NoteImageBreadcrumbs.Columns),
		NoteImageData:                      buildNoteImageDatumWhere[Q](NoteImageData.Columns),
		Notifications:                      buildNotificationWhere[Q](Notifications.Columns),
		OauthTokens:                        buildOauthTokenWhere[Q](OauthTokens.Columns),
		Organizations:                      buildOrganizationWhere[Q](Organizations.Columns),
		PublicreportNuisances:              buildPublicreportNuisanceWhere[Q](PublicreportNuisances.Columns),
		PublicreportPools:                  buildPublicreportPoolWhere[Q](PublicreportPools.Columns),
		PublicreportPoolPhotos:             buildPublicreportPoolPhotoWhere[Q](PublicreportPoolPhotos.Columns),
		PublicreportQuicks:                 buildPublicreportQuickWhere[Q](PublicreportQuicks.Columns),
		PublicreportQuickPhotos:            buildPublicreportQuickPhotoWhere[Q](PublicreportQuickPhotos.Columns),
		PublicreportReportLocations:        buildPublicreportReportLocationWhere[Q](PublicreportReportLocations.Columns),
		RasterColumns:                      buildRasterColumnWhere[Q](RasterColumns.Columns),
		RasterOverviews:                    buildRasterOverviewWhere[Q](RasterOverviews.Columns),
		Sessions:                           buildSessionWhere[Q](Sessions.Columns),
		SpatialRefSys:                      buildSpatialRefSyWhere[Q](SpatialRefSys.Columns),
		Users:                              buildUserWhere[Q](Users.Columns),
	}
}
