// Code generated by BobGen psql v0.0.3-0.20251202003046-49148fc66a73+dirty. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	enums "github.com/Gleipnir-Technology/nidus-sync/db/enums"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// FieldseekerPolygonlocation is an object representing the database table.
type FieldseekerPolygonlocation struct {
	Objectid int64 `db:"objectid,pk" `
	// Name
	Name null.Val[string] `db:"name" `
	// Zone
	Zone null.Val[string] `db:"zone" `
	// Habitat
	Habitat null.Val[enums.FieldseekerPolygonlocationPolygonlocationHabitat45e9dde79ac84d959df8b65] `db:"habitat" `
	// Priority
	Priority null.Val[enums.FieldseekerPolygonlocationLocationpriorityEnum] `db:"priority" `
	// Use Type
	Usetype null.Val[enums.FieldseekerPolygonlocationPolygonlocationUsetypeE546154cb9544b9aa8e7b13] `db:"usetype" `
	// Active
	Active null.Val[enums.FieldseekerPolygonlocationNotinuitFEnum] `db:"active" `
	// Description
	Description null.Val[string] `db:"description" `
	// Access Description
	Accessdesc null.Val[string] `db:"accessdesc" `
	// Comments
	Comments null.Val[string] `db:"comments" `
	// Symbology
	Symbology null.Val[enums.FieldseekerPolygonlocationLocationsymbologyEnum] `db:"symbology" `
	// External ID
	Externalid null.Val[string] `db:"externalid" `
	// Acres
	Acres null.Val[float64] `db:"acres" `
	// Next Scheduled Action
	Nextactiondatescheduled null.Val[time.Time] `db:"nextactiondatescheduled" `
	// Larval Inspection Interval
	Larvinspectinterval null.Val[int16] `db:"larvinspectinterval" `
	// Zone2
	Zone2          null.Val[string]    `db:"zone2" `
	Locationnumber null.Val[int32]     `db:"locationnumber" `
	Globalid       null.Val[uuid.UUID] `db:"globalid" `
	// Last Inspection Date
	Lastinspectdate null.Val[time.Time] `db:"lastinspectdate" `
	// Last Inspection Breeding
	Lastinspectbreeding null.Val[string] `db:"lastinspectbreeding" `
	// Last Inspection Average Larvae
	Lastinspectavglarvae null.Val[float64] `db:"lastinspectavglarvae" `
	// Last Inspection Average Pupae
	Lastinspectavgpupae null.Val[float64] `db:"lastinspectavgpupae" `
	// Last Inspection Larval Stages
	Lastinspectlstages null.Val[string] `db:"lastinspectlstages" `
	// Last Inspection Action
	Lastinspectactiontaken null.Val[string] `db:"lastinspectactiontaken" `
	// Last Inspection Field Species
	Lastinspectfieldspecies null.Val[string] `db:"lastinspectfieldspecies" `
	// Last Treatment Date
	Lasttreatdate null.Val[time.Time] `db:"lasttreatdate" `
	// Last Treatment Product
	Lasttreatproduct null.Val[string] `db:"lasttreatproduct" `
	// Last Treatment Quantity
	Lasttreatqty null.Val[float64] `db:"lasttreatqty" `
	// Last Treatment Quantity Unit
	Lasttreatqtyunit null.Val[string] `db:"lasttreatqtyunit" `
	// Hectares
	Hectares null.Val[float64] `db:"hectares" `
	// Last Inspection Activity
	Lastinspectactivity null.Val[string] `db:"lastinspectactivity" `
	// Last Treatment Activity
	Lasttreatactivity null.Val[string] `db:"lasttreatactivity" `
	// Last Inspection Conditions
	Lastinspectconditions null.Val[string] `db:"lastinspectconditions" `
	// Water Origin
	Waterorigin  null.Val[enums.FieldseekerPolygonlocationPolygonlocationWateroriginE9018e925F474FF9] `db:"waterorigin" `
	Filter       null.Val[string]                                                                     `db:"filter" `
	Creationdate null.Val[time.Time]                                                                  `db:"creationdate" `
	Creator      null.Val[string]                                                                     `db:"creator" `
	Editdate     null.Val[time.Time]                                                                  `db:"editdate" `
	Editor       null.Val[string]                                                                     `db:"editor" `
	// Jurisdiction
	Jurisdiction null.Val[string]  `db:"jurisdiction" `
	ShapeArea    null.Val[float64] `db:"shape__area" `
	ShapeLength  null.Val[float64] `db:"shape__length" `
	// Tracks version changes to the row. Increases when data is modified.
	Version int32 `db:"version,pk" `
}

// FieldseekerPolygonlocationSlice is an alias for a slice of pointers to FieldseekerPolygonlocation.
// This should almost always be used instead of []*FieldseekerPolygonlocation.
type FieldseekerPolygonlocationSlice []*FieldseekerPolygonlocation

// FieldseekerPolygonlocations contains methods to work with the polygonlocation table
var FieldseekerPolygonlocations = psql.NewTablex[*FieldseekerPolygonlocation, FieldseekerPolygonlocationSlice, *FieldseekerPolygonlocationSetter]("fieldseeker", "polygonlocation", buildFieldseekerPolygonlocationColumns("fieldseeker.polygonlocation"))

// FieldseekerPolygonlocationsQuery is a query on the polygonlocation table
type FieldseekerPolygonlocationsQuery = *psql.ViewQuery[*FieldseekerPolygonlocation, FieldseekerPolygonlocationSlice]

func buildFieldseekerPolygonlocationColumns(alias string) fieldseekerPolygonlocationColumns {
	return fieldseekerPolygonlocationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"objectid", "name", "zone", "habitat", "priority", "usetype", "active", "description", "accessdesc", "comments", "symbology", "externalid", "acres", "nextactiondatescheduled", "larvinspectinterval", "zone2", "locationnumber", "globalid", "lastinspectdate", "lastinspectbreeding", "lastinspectavglarvae", "lastinspectavgpupae", "lastinspectlstages", "lastinspectactiontaken", "lastinspectfieldspecies", "lasttreatdate", "lasttreatproduct", "lasttreatqty", "lasttreatqtyunit", "hectares", "lastinspectactivity", "lasttreatactivity", "lastinspectconditions", "waterorigin", "filter", "creationdate", "creator", "editdate", "editor", "jurisdiction", "shape__area", "shape__length", "version",
		).WithParent("fieldseeker.polygonlocation"),
		tableAlias:              alias,
		Objectid:                psql.Quote(alias, "objectid"),
		Name:                    psql.Quote(alias, "name"),
		Zone:                    psql.Quote(alias, "zone"),
		Habitat:                 psql.Quote(alias, "habitat"),
		Priority:                psql.Quote(alias, "priority"),
		Usetype:                 psql.Quote(alias, "usetype"),
		Active:                  psql.Quote(alias, "active"),
		Description:             psql.Quote(alias, "description"),
		Accessdesc:              psql.Quote(alias, "accessdesc"),
		Comments:                psql.Quote(alias, "comments"),
		Symbology:               psql.Quote(alias, "symbology"),
		Externalid:              psql.Quote(alias, "externalid"),
		Acres:                   psql.Quote(alias, "acres"),
		Nextactiondatescheduled: psql.Quote(alias, "nextactiondatescheduled"),
		Larvinspectinterval:     psql.Quote(alias, "larvinspectinterval"),
		Zone2:                   psql.Quote(alias, "zone2"),
		Locationnumber:          psql.Quote(alias, "locationnumber"),
		Globalid:                psql.Quote(alias, "globalid"),
		Lastinspectdate:         psql.Quote(alias, "lastinspectdate"),
		Lastinspectbreeding:     psql.Quote(alias, "lastinspectbreeding"),
		Lastinspectavglarvae:    psql.Quote(alias, "lastinspectavglarvae"),
		Lastinspectavgpupae:     psql.Quote(alias, "lastinspectavgpupae"),
		Lastinspectlstages:      psql.Quote(alias, "lastinspectlstages"),
		Lastinspectactiontaken:  psql.Quote(alias, "lastinspectactiontaken"),
		Lastinspectfieldspecies: psql.Quote(alias, "lastinspectfieldspecies"),
		Lasttreatdate:           psql.Quote(alias, "lasttreatdate"),
		Lasttreatproduct:        psql.Quote(alias, "lasttreatproduct"),
		Lasttreatqty:            psql.Quote(alias, "lasttreatqty"),
		Lasttreatqtyunit:        psql.Quote(alias, "lasttreatqtyunit"),
		Hectares:                psql.Quote(alias, "hectares"),
		Lastinspectactivity:     psql.Quote(alias, "lastinspectactivity"),
		Lasttreatactivity:       psql.Quote(alias, "lasttreatactivity"),
		Lastinspectconditions:   psql.Quote(alias, "lastinspectconditions"),
		Waterorigin:             psql.Quote(alias, "waterorigin"),
		Filter:                  psql.Quote(alias, "filter"),
		Creationdate:            psql.Quote(alias, "creationdate"),
		Creator:                 psql.Quote(alias, "creator"),
		Editdate:                psql.Quote(alias, "editdate"),
		Editor:                  psql.Quote(alias, "editor"),
		Jurisdiction:            psql.Quote(alias, "jurisdiction"),
		ShapeArea:               psql.Quote(alias, "shape__area"),
		ShapeLength:             psql.Quote(alias, "shape__length"),
		Version:                 psql.Quote(alias, "version"),
	}
}

type fieldseekerPolygonlocationColumns struct {
	expr.ColumnsExpr
	tableAlias              string
	Objectid                psql.Expression
	Name                    psql.Expression
	Zone                    psql.Expression
	Habitat                 psql.Expression
	Priority                psql.Expression
	Usetype                 psql.Expression
	Active                  psql.Expression
	Description             psql.Expression
	Accessdesc              psql.Expression
	Comments                psql.Expression
	Symbology               psql.Expression
	Externalid              psql.Expression
	Acres                   psql.Expression
	Nextactiondatescheduled psql.Expression
	Larvinspectinterval     psql.Expression
	Zone2                   psql.Expression
	Locationnumber          psql.Expression
	Globalid                psql.Expression
	Lastinspectdate         psql.Expression
	Lastinspectbreeding     psql.Expression
	Lastinspectavglarvae    psql.Expression
	Lastinspectavgpupae     psql.Expression
	Lastinspectlstages      psql.Expression
	Lastinspectactiontaken  psql.Expression
	Lastinspectfieldspecies psql.Expression
	Lasttreatdate           psql.Expression
	Lasttreatproduct        psql.Expression
	Lasttreatqty            psql.Expression
	Lasttreatqtyunit        psql.Expression
	Hectares                psql.Expression
	Lastinspectactivity     psql.Expression
	Lasttreatactivity       psql.Expression
	Lastinspectconditions   psql.Expression
	Waterorigin             psql.Expression
	Filter                  psql.Expression
	Creationdate            psql.Expression
	Creator                 psql.Expression
	Editdate                psql.Expression
	Editor                  psql.Expression
	Jurisdiction            psql.Expression
	ShapeArea               psql.Expression
	ShapeLength             psql.Expression
	Version                 psql.Expression
}

func (c fieldseekerPolygonlocationColumns) Alias() string {
	return c.tableAlias
}

func (fieldseekerPolygonlocationColumns) AliasedAs(alias string) fieldseekerPolygonlocationColumns {
	return buildFieldseekerPolygonlocationColumns(alias)
}

// FieldseekerPolygonlocationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type FieldseekerPolygonlocationSetter struct {
	Objectid                omit.Val[int64]                                                                             `db:"objectid,pk" `
	Name                    omitnull.Val[string]                                                                        `db:"name" `
	Zone                    omitnull.Val[string]                                                                        `db:"zone" `
	Habitat                 omitnull.Val[enums.FieldseekerPolygonlocationPolygonlocationHabitat45e9dde79ac84d959df8b65] `db:"habitat" `
	Priority                omitnull.Val[enums.FieldseekerPolygonlocationLocationpriorityEnum]                          `db:"priority" `
	Usetype                 omitnull.Val[enums.FieldseekerPolygonlocationPolygonlocationUsetypeE546154cb9544b9aa8e7b13] `db:"usetype" `
	Active                  omitnull.Val[enums.FieldseekerPolygonlocationNotinuitFEnum]                                 `db:"active" `
	Description             omitnull.Val[string]                                                                        `db:"description" `
	Accessdesc              omitnull.Val[string]                                                                        `db:"accessdesc" `
	Comments                omitnull.Val[string]                                                                        `db:"comments" `
	Symbology               omitnull.Val[enums.FieldseekerPolygonlocationLocationsymbologyEnum]                         `db:"symbology" `
	Externalid              omitnull.Val[string]                                                                        `db:"externalid" `
	Acres                   omitnull.Val[float64]                                                                       `db:"acres" `
	Nextactiondatescheduled omitnull.Val[time.Time]                                                                     `db:"nextactiondatescheduled" `
	Larvinspectinterval     omitnull.Val[int16]                                                                         `db:"larvinspectinterval" `
	Zone2                   omitnull.Val[string]                                                                        `db:"zone2" `
	Locationnumber          omitnull.Val[int32]                                                                         `db:"locationnumber" `
	Globalid                omitnull.Val[uuid.UUID]                                                                     `db:"globalid" `
	Lastinspectdate         omitnull.Val[time.Time]                                                                     `db:"lastinspectdate" `
	Lastinspectbreeding     omitnull.Val[string]                                                                        `db:"lastinspectbreeding" `
	Lastinspectavglarvae    omitnull.Val[float64]                                                                       `db:"lastinspectavglarvae" `
	Lastinspectavgpupae     omitnull.Val[float64]                                                                       `db:"lastinspectavgpupae" `
	Lastinspectlstages      omitnull.Val[string]                                                                        `db:"lastinspectlstages" `
	Lastinspectactiontaken  omitnull.Val[string]                                                                        `db:"lastinspectactiontaken" `
	Lastinspectfieldspecies omitnull.Val[string]                                                                        `db:"lastinspectfieldspecies" `
	Lasttreatdate           omitnull.Val[time.Time]                                                                     `db:"lasttreatdate" `
	Lasttreatproduct        omitnull.Val[string]                                                                        `db:"lasttreatproduct" `
	Lasttreatqty            omitnull.Val[float64]                                                                       `db:"lasttreatqty" `
	Lasttreatqtyunit        omitnull.Val[string]                                                                        `db:"lasttreatqtyunit" `
	Hectares                omitnull.Val[float64]                                                                       `db:"hectares" `
	Lastinspectactivity     omitnull.Val[string]                                                                        `db:"lastinspectactivity" `
	Lasttreatactivity       omitnull.Val[string]                                                                        `db:"lasttreatactivity" `
	Lastinspectconditions   omitnull.Val[string]                                                                        `db:"lastinspectconditions" `
	Waterorigin             omitnull.Val[enums.FieldseekerPolygonlocationPolygonlocationWateroriginE9018e925F474FF9]    `db:"waterorigin" `
	Filter                  omitnull.Val[string]                                                                        `db:"filter" `
	Creationdate            omitnull.Val[time.Time]                                                                     `db:"creationdate" `
	Creator                 omitnull.Val[string]                                                                        `db:"creator" `
	Editdate                omitnull.Val[time.Time]                                                                     `db:"editdate" `
	Editor                  omitnull.Val[string]                                                                        `db:"editor" `
	Jurisdiction            omitnull.Val[string]                                                                        `db:"jurisdiction" `
	ShapeArea               omitnull.Val[float64]                                                                       `db:"shape__area" `
	ShapeLength             omitnull.Val[float64]                                                                       `db:"shape__length" `
	Version                 omit.Val[int32]                                                                             `db:"version,pk" `
}

func (s FieldseekerPolygonlocationSetter) SetColumns() []string {
	vals := make([]string, 0, 43)
	if s.Objectid.IsValue() {
		vals = append(vals, "objectid")
	}
	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}
	if !s.Zone.IsUnset() {
		vals = append(vals, "zone")
	}
	if !s.Habitat.IsUnset() {
		vals = append(vals, "habitat")
	}
	if !s.Priority.IsUnset() {
		vals = append(vals, "priority")
	}
	if !s.Usetype.IsUnset() {
		vals = append(vals, "usetype")
	}
	if !s.Active.IsUnset() {
		vals = append(vals, "active")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if !s.Accessdesc.IsUnset() {
		vals = append(vals, "accessdesc")
	}
	if !s.Comments.IsUnset() {
		vals = append(vals, "comments")
	}
	if !s.Symbology.IsUnset() {
		vals = append(vals, "symbology")
	}
	if !s.Externalid.IsUnset() {
		vals = append(vals, "externalid")
	}
	if !s.Acres.IsUnset() {
		vals = append(vals, "acres")
	}
	if !s.Nextactiondatescheduled.IsUnset() {
		vals = append(vals, "nextactiondatescheduled")
	}
	if !s.Larvinspectinterval.IsUnset() {
		vals = append(vals, "larvinspectinterval")
	}
	if !s.Zone2.IsUnset() {
		vals = append(vals, "zone2")
	}
	if !s.Locationnumber.IsUnset() {
		vals = append(vals, "locationnumber")
	}
	if !s.Globalid.IsUnset() {
		vals = append(vals, "globalid")
	}
	if !s.Lastinspectdate.IsUnset() {
		vals = append(vals, "lastinspectdate")
	}
	if !s.Lastinspectbreeding.IsUnset() {
		vals = append(vals, "lastinspectbreeding")
	}
	if !s.Lastinspectavglarvae.IsUnset() {
		vals = append(vals, "lastinspectavglarvae")
	}
	if !s.Lastinspectavgpupae.IsUnset() {
		vals = append(vals, "lastinspectavgpupae")
	}
	if !s.Lastinspectlstages.IsUnset() {
		vals = append(vals, "lastinspectlstages")
	}
	if !s.Lastinspectactiontaken.IsUnset() {
		vals = append(vals, "lastinspectactiontaken")
	}
	if !s.Lastinspectfieldspecies.IsUnset() {
		vals = append(vals, "lastinspectfieldspecies")
	}
	if !s.Lasttreatdate.IsUnset() {
		vals = append(vals, "lasttreatdate")
	}
	if !s.Lasttreatproduct.IsUnset() {
		vals = append(vals, "lasttreatproduct")
	}
	if !s.Lasttreatqty.IsUnset() {
		vals = append(vals, "lasttreatqty")
	}
	if !s.Lasttreatqtyunit.IsUnset() {
		vals = append(vals, "lasttreatqtyunit")
	}
	if !s.Hectares.IsUnset() {
		vals = append(vals, "hectares")
	}
	if !s.Lastinspectactivity.IsUnset() {
		vals = append(vals, "lastinspectactivity")
	}
	if !s.Lasttreatactivity.IsUnset() {
		vals = append(vals, "lasttreatactivity")
	}
	if !s.Lastinspectconditions.IsUnset() {
		vals = append(vals, "lastinspectconditions")
	}
	if !s.Waterorigin.IsUnset() {
		vals = append(vals, "waterorigin")
	}
	if !s.Filter.IsUnset() {
		vals = append(vals, "filter")
	}
	if !s.Creationdate.IsUnset() {
		vals = append(vals, "creationdate")
	}
	if !s.Creator.IsUnset() {
		vals = append(vals, "creator")
	}
	if !s.Editdate.IsUnset() {
		vals = append(vals, "editdate")
	}
	if !s.Editor.IsUnset() {
		vals = append(vals, "editor")
	}
	if !s.Jurisdiction.IsUnset() {
		vals = append(vals, "jurisdiction")
	}
	if !s.ShapeArea.IsUnset() {
		vals = append(vals, "shape__area")
	}
	if !s.ShapeLength.IsUnset() {
		vals = append(vals, "shape__length")
	}
	if s.Version.IsValue() {
		vals = append(vals, "version")
	}
	return vals
}

func (s FieldseekerPolygonlocationSetter) Overwrite(t *FieldseekerPolygonlocation) {
	if s.Objectid.IsValue() {
		t.Objectid = s.Objectid.MustGet()
	}
	if !s.Name.IsUnset() {
		t.Name = s.Name.MustGetNull()
	}
	if !s.Zone.IsUnset() {
		t.Zone = s.Zone.MustGetNull()
	}
	if !s.Habitat.IsUnset() {
		t.Habitat = s.Habitat.MustGetNull()
	}
	if !s.Priority.IsUnset() {
		t.Priority = s.Priority.MustGetNull()
	}
	if !s.Usetype.IsUnset() {
		t.Usetype = s.Usetype.MustGetNull()
	}
	if !s.Active.IsUnset() {
		t.Active = s.Active.MustGetNull()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if !s.Accessdesc.IsUnset() {
		t.Accessdesc = s.Accessdesc.MustGetNull()
	}
	if !s.Comments.IsUnset() {
		t.Comments = s.Comments.MustGetNull()
	}
	if !s.Symbology.IsUnset() {
		t.Symbology = s.Symbology.MustGetNull()
	}
	if !s.Externalid.IsUnset() {
		t.Externalid = s.Externalid.MustGetNull()
	}
	if !s.Acres.IsUnset() {
		t.Acres = s.Acres.MustGetNull()
	}
	if !s.Nextactiondatescheduled.IsUnset() {
		t.Nextactiondatescheduled = s.Nextactiondatescheduled.MustGetNull()
	}
	if !s.Larvinspectinterval.IsUnset() {
		t.Larvinspectinterval = s.Larvinspectinterval.MustGetNull()
	}
	if !s.Zone2.IsUnset() {
		t.Zone2 = s.Zone2.MustGetNull()
	}
	if !s.Locationnumber.IsUnset() {
		t.Locationnumber = s.Locationnumber.MustGetNull()
	}
	if !s.Globalid.IsUnset() {
		t.Globalid = s.Globalid.MustGetNull()
	}
	if !s.Lastinspectdate.IsUnset() {
		t.Lastinspectdate = s.Lastinspectdate.MustGetNull()
	}
	if !s.Lastinspectbreeding.IsUnset() {
		t.Lastinspectbreeding = s.Lastinspectbreeding.MustGetNull()
	}
	if !s.Lastinspectavglarvae.IsUnset() {
		t.Lastinspectavglarvae = s.Lastinspectavglarvae.MustGetNull()
	}
	if !s.Lastinspectavgpupae.IsUnset() {
		t.Lastinspectavgpupae = s.Lastinspectavgpupae.MustGetNull()
	}
	if !s.Lastinspectlstages.IsUnset() {
		t.Lastinspectlstages = s.Lastinspectlstages.MustGetNull()
	}
	if !s.Lastinspectactiontaken.IsUnset() {
		t.Lastinspectactiontaken = s.Lastinspectactiontaken.MustGetNull()
	}
	if !s.Lastinspectfieldspecies.IsUnset() {
		t.Lastinspectfieldspecies = s.Lastinspectfieldspecies.MustGetNull()
	}
	if !s.Lasttreatdate.IsUnset() {
		t.Lasttreatdate = s.Lasttreatdate.MustGetNull()
	}
	if !s.Lasttreatproduct.IsUnset() {
		t.Lasttreatproduct = s.Lasttreatproduct.MustGetNull()
	}
	if !s.Lasttreatqty.IsUnset() {
		t.Lasttreatqty = s.Lasttreatqty.MustGetNull()
	}
	if !s.Lasttreatqtyunit.IsUnset() {
		t.Lasttreatqtyunit = s.Lasttreatqtyunit.MustGetNull()
	}
	if !s.Hectares.IsUnset() {
		t.Hectares = s.Hectares.MustGetNull()
	}
	if !s.Lastinspectactivity.IsUnset() {
		t.Lastinspectactivity = s.Lastinspectactivity.MustGetNull()
	}
	if !s.Lasttreatactivity.IsUnset() {
		t.Lasttreatactivity = s.Lasttreatactivity.MustGetNull()
	}
	if !s.Lastinspectconditions.IsUnset() {
		t.Lastinspectconditions = s.Lastinspectconditions.MustGetNull()
	}
	if !s.Waterorigin.IsUnset() {
		t.Waterorigin = s.Waterorigin.MustGetNull()
	}
	if !s.Filter.IsUnset() {
		t.Filter = s.Filter.MustGetNull()
	}
	if !s.Creationdate.IsUnset() {
		t.Creationdate = s.Creationdate.MustGetNull()
	}
	if !s.Creator.IsUnset() {
		t.Creator = s.Creator.MustGetNull()
	}
	if !s.Editdate.IsUnset() {
		t.Editdate = s.Editdate.MustGetNull()
	}
	if !s.Editor.IsUnset() {
		t.Editor = s.Editor.MustGetNull()
	}
	if !s.Jurisdiction.IsUnset() {
		t.Jurisdiction = s.Jurisdiction.MustGetNull()
	}
	if !s.ShapeArea.IsUnset() {
		t.ShapeArea = s.ShapeArea.MustGetNull()
	}
	if !s.ShapeLength.IsUnset() {
		t.ShapeLength = s.ShapeLength.MustGetNull()
	}
	if s.Version.IsValue() {
		t.Version = s.Version.MustGet()
	}
}

func (s *FieldseekerPolygonlocationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return FieldseekerPolygonlocations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 43)
		if s.Objectid.IsValue() {
			vals[0] = psql.Arg(s.Objectid.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if !s.Name.IsUnset() {
			vals[1] = psql.Arg(s.Name.MustGetNull())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.Zone.IsUnset() {
			vals[2] = psql.Arg(s.Zone.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Habitat.IsUnset() {
			vals[3] = psql.Arg(s.Habitat.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Priority.IsUnset() {
			vals[4] = psql.Arg(s.Priority.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Usetype.IsUnset() {
			vals[5] = psql.Arg(s.Usetype.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.Active.IsUnset() {
			vals[6] = psql.Arg(s.Active.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[7] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.Accessdesc.IsUnset() {
			vals[8] = psql.Arg(s.Accessdesc.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.Comments.IsUnset() {
			vals[9] = psql.Arg(s.Comments.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.Symbology.IsUnset() {
			vals[10] = psql.Arg(s.Symbology.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if !s.Externalid.IsUnset() {
			vals[11] = psql.Arg(s.Externalid.MustGetNull())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if !s.Acres.IsUnset() {
			vals[12] = psql.Arg(s.Acres.MustGetNull())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if !s.Nextactiondatescheduled.IsUnset() {
			vals[13] = psql.Arg(s.Nextactiondatescheduled.MustGetNull())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if !s.Larvinspectinterval.IsUnset() {
			vals[14] = psql.Arg(s.Larvinspectinterval.MustGetNull())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if !s.Zone2.IsUnset() {
			vals[15] = psql.Arg(s.Zone2.MustGetNull())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		if !s.Locationnumber.IsUnset() {
			vals[16] = psql.Arg(s.Locationnumber.MustGetNull())
		} else {
			vals[16] = psql.Raw("DEFAULT")
		}

		if !s.Globalid.IsUnset() {
			vals[17] = psql.Arg(s.Globalid.MustGetNull())
		} else {
			vals[17] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectdate.IsUnset() {
			vals[18] = psql.Arg(s.Lastinspectdate.MustGetNull())
		} else {
			vals[18] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectbreeding.IsUnset() {
			vals[19] = psql.Arg(s.Lastinspectbreeding.MustGetNull())
		} else {
			vals[19] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectavglarvae.IsUnset() {
			vals[20] = psql.Arg(s.Lastinspectavglarvae.MustGetNull())
		} else {
			vals[20] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectavgpupae.IsUnset() {
			vals[21] = psql.Arg(s.Lastinspectavgpupae.MustGetNull())
		} else {
			vals[21] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectlstages.IsUnset() {
			vals[22] = psql.Arg(s.Lastinspectlstages.MustGetNull())
		} else {
			vals[22] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectactiontaken.IsUnset() {
			vals[23] = psql.Arg(s.Lastinspectactiontaken.MustGetNull())
		} else {
			vals[23] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectfieldspecies.IsUnset() {
			vals[24] = psql.Arg(s.Lastinspectfieldspecies.MustGetNull())
		} else {
			vals[24] = psql.Raw("DEFAULT")
		}

		if !s.Lasttreatdate.IsUnset() {
			vals[25] = psql.Arg(s.Lasttreatdate.MustGetNull())
		} else {
			vals[25] = psql.Raw("DEFAULT")
		}

		if !s.Lasttreatproduct.IsUnset() {
			vals[26] = psql.Arg(s.Lasttreatproduct.MustGetNull())
		} else {
			vals[26] = psql.Raw("DEFAULT")
		}

		if !s.Lasttreatqty.IsUnset() {
			vals[27] = psql.Arg(s.Lasttreatqty.MustGetNull())
		} else {
			vals[27] = psql.Raw("DEFAULT")
		}

		if !s.Lasttreatqtyunit.IsUnset() {
			vals[28] = psql.Arg(s.Lasttreatqtyunit.MustGetNull())
		} else {
			vals[28] = psql.Raw("DEFAULT")
		}

		if !s.Hectares.IsUnset() {
			vals[29] = psql.Arg(s.Hectares.MustGetNull())
		} else {
			vals[29] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectactivity.IsUnset() {
			vals[30] = psql.Arg(s.Lastinspectactivity.MustGetNull())
		} else {
			vals[30] = psql.Raw("DEFAULT")
		}

		if !s.Lasttreatactivity.IsUnset() {
			vals[31] = psql.Arg(s.Lasttreatactivity.MustGetNull())
		} else {
			vals[31] = psql.Raw("DEFAULT")
		}

		if !s.Lastinspectconditions.IsUnset() {
			vals[32] = psql.Arg(s.Lastinspectconditions.MustGetNull())
		} else {
			vals[32] = psql.Raw("DEFAULT")
		}

		if !s.Waterorigin.IsUnset() {
			vals[33] = psql.Arg(s.Waterorigin.MustGetNull())
		} else {
			vals[33] = psql.Raw("DEFAULT")
		}

		if !s.Filter.IsUnset() {
			vals[34] = psql.Arg(s.Filter.MustGetNull())
		} else {
			vals[34] = psql.Raw("DEFAULT")
		}

		if !s.Creationdate.IsUnset() {
			vals[35] = psql.Arg(s.Creationdate.MustGetNull())
		} else {
			vals[35] = psql.Raw("DEFAULT")
		}

		if !s.Creator.IsUnset() {
			vals[36] = psql.Arg(s.Creator.MustGetNull())
		} else {
			vals[36] = psql.Raw("DEFAULT")
		}

		if !s.Editdate.IsUnset() {
			vals[37] = psql.Arg(s.Editdate.MustGetNull())
		} else {
			vals[37] = psql.Raw("DEFAULT")
		}

		if !s.Editor.IsUnset() {
			vals[38] = psql.Arg(s.Editor.MustGetNull())
		} else {
			vals[38] = psql.Raw("DEFAULT")
		}

		if !s.Jurisdiction.IsUnset() {
			vals[39] = psql.Arg(s.Jurisdiction.MustGetNull())
		} else {
			vals[39] = psql.Raw("DEFAULT")
		}

		if !s.ShapeArea.IsUnset() {
			vals[40] = psql.Arg(s.ShapeArea.MustGetNull())
		} else {
			vals[40] = psql.Raw("DEFAULT")
		}

		if !s.ShapeLength.IsUnset() {
			vals[41] = psql.Arg(s.ShapeLength.MustGetNull())
		} else {
			vals[41] = psql.Raw("DEFAULT")
		}

		if s.Version.IsValue() {
			vals[42] = psql.Arg(s.Version.MustGet())
		} else {
			vals[42] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s FieldseekerPolygonlocationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s FieldseekerPolygonlocationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 43)

	if s.Objectid.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "objectid")...),
			psql.Arg(s.Objectid),
		}})
	}

	if !s.Name.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if !s.Zone.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "zone")...),
			psql.Arg(s.Zone),
		}})
	}

	if !s.Habitat.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "habitat")...),
			psql.Arg(s.Habitat),
		}})
	}

	if !s.Priority.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "priority")...),
			psql.Arg(s.Priority),
		}})
	}

	if !s.Usetype.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "usetype")...),
			psql.Arg(s.Usetype),
		}})
	}

	if !s.Active.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "active")...),
			psql.Arg(s.Active),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if !s.Accessdesc.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "accessdesc")...),
			psql.Arg(s.Accessdesc),
		}})
	}

	if !s.Comments.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "comments")...),
			psql.Arg(s.Comments),
		}})
	}

	if !s.Symbology.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "symbology")...),
			psql.Arg(s.Symbology),
		}})
	}

	if !s.Externalid.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "externalid")...),
			psql.Arg(s.Externalid),
		}})
	}

	if !s.Acres.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "acres")...),
			psql.Arg(s.Acres),
		}})
	}

	if !s.Nextactiondatescheduled.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "nextactiondatescheduled")...),
			psql.Arg(s.Nextactiondatescheduled),
		}})
	}

	if !s.Larvinspectinterval.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "larvinspectinterval")...),
			psql.Arg(s.Larvinspectinterval),
		}})
	}

	if !s.Zone2.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "zone2")...),
			psql.Arg(s.Zone2),
		}})
	}

	if !s.Locationnumber.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "locationnumber")...),
			psql.Arg(s.Locationnumber),
		}})
	}

	if !s.Globalid.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "globalid")...),
			psql.Arg(s.Globalid),
		}})
	}

	if !s.Lastinspectdate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectdate")...),
			psql.Arg(s.Lastinspectdate),
		}})
	}

	if !s.Lastinspectbreeding.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectbreeding")...),
			psql.Arg(s.Lastinspectbreeding),
		}})
	}

	if !s.Lastinspectavglarvae.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectavglarvae")...),
			psql.Arg(s.Lastinspectavglarvae),
		}})
	}

	if !s.Lastinspectavgpupae.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectavgpupae")...),
			psql.Arg(s.Lastinspectavgpupae),
		}})
	}

	if !s.Lastinspectlstages.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectlstages")...),
			psql.Arg(s.Lastinspectlstages),
		}})
	}

	if !s.Lastinspectactiontaken.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectactiontaken")...),
			psql.Arg(s.Lastinspectactiontaken),
		}})
	}

	if !s.Lastinspectfieldspecies.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectfieldspecies")...),
			psql.Arg(s.Lastinspectfieldspecies),
		}})
	}

	if !s.Lasttreatdate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lasttreatdate")...),
			psql.Arg(s.Lasttreatdate),
		}})
	}

	if !s.Lasttreatproduct.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lasttreatproduct")...),
			psql.Arg(s.Lasttreatproduct),
		}})
	}

	if !s.Lasttreatqty.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lasttreatqty")...),
			psql.Arg(s.Lasttreatqty),
		}})
	}

	if !s.Lasttreatqtyunit.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lasttreatqtyunit")...),
			psql.Arg(s.Lasttreatqtyunit),
		}})
	}

	if !s.Hectares.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "hectares")...),
			psql.Arg(s.Hectares),
		}})
	}

	if !s.Lastinspectactivity.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectactivity")...),
			psql.Arg(s.Lastinspectactivity),
		}})
	}

	if !s.Lasttreatactivity.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lasttreatactivity")...),
			psql.Arg(s.Lasttreatactivity),
		}})
	}

	if !s.Lastinspectconditions.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastinspectconditions")...),
			psql.Arg(s.Lastinspectconditions),
		}})
	}

	if !s.Waterorigin.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "waterorigin")...),
			psql.Arg(s.Waterorigin),
		}})
	}

	if !s.Filter.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "filter")...),
			psql.Arg(s.Filter),
		}})
	}

	if !s.Creationdate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "creationdate")...),
			psql.Arg(s.Creationdate),
		}})
	}

	if !s.Creator.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "creator")...),
			psql.Arg(s.Creator),
		}})
	}

	if !s.Editdate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "editdate")...),
			psql.Arg(s.Editdate),
		}})
	}

	if !s.Editor.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "editor")...),
			psql.Arg(s.Editor),
		}})
	}

	if !s.Jurisdiction.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "jurisdiction")...),
			psql.Arg(s.Jurisdiction),
		}})
	}

	if !s.ShapeArea.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "shape__area")...),
			psql.Arg(s.ShapeArea),
		}})
	}

	if !s.ShapeLength.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "shape__length")...),
			psql.Arg(s.ShapeLength),
		}})
	}

	if s.Version.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "version")...),
			psql.Arg(s.Version),
		}})
	}

	return exprs
}

// FindFieldseekerPolygonlocation retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindFieldseekerPolygonlocation(ctx context.Context, exec bob.Executor, ObjectidPK int64, VersionPK int32, cols ...string) (*FieldseekerPolygonlocation, error) {
	if len(cols) == 0 {
		return FieldseekerPolygonlocations.Query(
			sm.Where(FieldseekerPolygonlocations.Columns.Objectid.EQ(psql.Arg(ObjectidPK))),
			sm.Where(FieldseekerPolygonlocations.Columns.Version.EQ(psql.Arg(VersionPK))),
		).One(ctx, exec)
	}

	return FieldseekerPolygonlocations.Query(
		sm.Where(FieldseekerPolygonlocations.Columns.Objectid.EQ(psql.Arg(ObjectidPK))),
		sm.Where(FieldseekerPolygonlocations.Columns.Version.EQ(psql.Arg(VersionPK))),
		sm.Columns(FieldseekerPolygonlocations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// FieldseekerPolygonlocationExists checks the presence of a single record by primary key
func FieldseekerPolygonlocationExists(ctx context.Context, exec bob.Executor, ObjectidPK int64, VersionPK int32) (bool, error) {
	return FieldseekerPolygonlocations.Query(
		sm.Where(FieldseekerPolygonlocations.Columns.Objectid.EQ(psql.Arg(ObjectidPK))),
		sm.Where(FieldseekerPolygonlocations.Columns.Version.EQ(psql.Arg(VersionPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after FieldseekerPolygonlocation is retrieved from the database
func (o *FieldseekerPolygonlocation) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FieldseekerPolygonlocations.AfterSelectHooks.RunHooks(ctx, exec, FieldseekerPolygonlocationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = FieldseekerPolygonlocations.AfterInsertHooks.RunHooks(ctx, exec, FieldseekerPolygonlocationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = FieldseekerPolygonlocations.AfterUpdateHooks.RunHooks(ctx, exec, FieldseekerPolygonlocationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = FieldseekerPolygonlocations.AfterDeleteHooks.RunHooks(ctx, exec, FieldseekerPolygonlocationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the FieldseekerPolygonlocation
func (o *FieldseekerPolygonlocation) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.Objectid,
		o.Version,
	)
}

func (o *FieldseekerPolygonlocation) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("fieldseeker.polygonlocation", "objectid"), psql.Quote("fieldseeker.polygonlocation", "version")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the FieldseekerPolygonlocation
func (o *FieldseekerPolygonlocation) Update(ctx context.Context, exec bob.Executor, s *FieldseekerPolygonlocationSetter) error {
	v, err := FieldseekerPolygonlocations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single FieldseekerPolygonlocation record with an executor
func (o *FieldseekerPolygonlocation) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := FieldseekerPolygonlocations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the FieldseekerPolygonlocation using the executor
func (o *FieldseekerPolygonlocation) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := FieldseekerPolygonlocations.Query(
		sm.Where(FieldseekerPolygonlocations.Columns.Objectid.EQ(psql.Arg(o.Objectid))),
		sm.Where(FieldseekerPolygonlocations.Columns.Version.EQ(psql.Arg(o.Version))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after FieldseekerPolygonlocationSlice is retrieved from the database
func (o FieldseekerPolygonlocationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FieldseekerPolygonlocations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = FieldseekerPolygonlocations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = FieldseekerPolygonlocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = FieldseekerPolygonlocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o FieldseekerPolygonlocationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("fieldseeker.polygonlocation", "objectid"), psql.Quote("fieldseeker.polygonlocation", "version")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o FieldseekerPolygonlocationSlice) copyMatchingRows(from ...*FieldseekerPolygonlocation) {
	for i, old := range o {
		for _, new := range from {
			if new.Objectid != old.Objectid {
				continue
			}
			if new.Version != old.Version {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o FieldseekerPolygonlocationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FieldseekerPolygonlocations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FieldseekerPolygonlocation:
				o.copyMatchingRows(retrieved)
			case []*FieldseekerPolygonlocation:
				o.copyMatchingRows(retrieved...)
			case FieldseekerPolygonlocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FieldseekerPolygonlocation or a slice of FieldseekerPolygonlocation
				// then run the AfterUpdateHooks on the slice
				_, err = FieldseekerPolygonlocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o FieldseekerPolygonlocationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FieldseekerPolygonlocations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FieldseekerPolygonlocation:
				o.copyMatchingRows(retrieved)
			case []*FieldseekerPolygonlocation:
				o.copyMatchingRows(retrieved...)
			case FieldseekerPolygonlocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FieldseekerPolygonlocation or a slice of FieldseekerPolygonlocation
				// then run the AfterDeleteHooks on the slice
				_, err = FieldseekerPolygonlocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o FieldseekerPolygonlocationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals FieldseekerPolygonlocationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := FieldseekerPolygonlocations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o FieldseekerPolygonlocationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := FieldseekerPolygonlocations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o FieldseekerPolygonlocationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := FieldseekerPolygonlocations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type fieldseekerPolygonlocationWhere[Q psql.Filterable] struct {
	Objectid                psql.WhereMod[Q, int64]
	Name                    psql.WhereNullMod[Q, string]
	Zone                    psql.WhereNullMod[Q, string]
	Habitat                 psql.WhereNullMod[Q, enums.FieldseekerPolygonlocationPolygonlocationHabitat45e9dde79ac84d959df8b65]
	Priority                psql.WhereNullMod[Q, enums.FieldseekerPolygonlocationLocationpriorityEnum]
	Usetype                 psql.WhereNullMod[Q, enums.FieldseekerPolygonlocationPolygonlocationUsetypeE546154cb9544b9aa8e7b13]
	Active                  psql.WhereNullMod[Q, enums.FieldseekerPolygonlocationNotinuitFEnum]
	Description             psql.WhereNullMod[Q, string]
	Accessdesc              psql.WhereNullMod[Q, string]
	Comments                psql.WhereNullMod[Q, string]
	Symbology               psql.WhereNullMod[Q, enums.FieldseekerPolygonlocationLocationsymbologyEnum]
	Externalid              psql.WhereNullMod[Q, string]
	Acres                   psql.WhereNullMod[Q, float64]
	Nextactiondatescheduled psql.WhereNullMod[Q, time.Time]
	Larvinspectinterval     psql.WhereNullMod[Q, int16]
	Zone2                   psql.WhereNullMod[Q, string]
	Locationnumber          psql.WhereNullMod[Q, int32]
	Globalid                psql.WhereNullMod[Q, uuid.UUID]
	Lastinspectdate         psql.WhereNullMod[Q, time.Time]
	Lastinspectbreeding     psql.WhereNullMod[Q, string]
	Lastinspectavglarvae    psql.WhereNullMod[Q, float64]
	Lastinspectavgpupae     psql.WhereNullMod[Q, float64]
	Lastinspectlstages      psql.WhereNullMod[Q, string]
	Lastinspectactiontaken  psql.WhereNullMod[Q, string]
	Lastinspectfieldspecies psql.WhereNullMod[Q, string]
	Lasttreatdate           psql.WhereNullMod[Q, time.Time]
	Lasttreatproduct        psql.WhereNullMod[Q, string]
	Lasttreatqty            psql.WhereNullMod[Q, float64]
	Lasttreatqtyunit        psql.WhereNullMod[Q, string]
	Hectares                psql.WhereNullMod[Q, float64]
	Lastinspectactivity     psql.WhereNullMod[Q, string]
	Lasttreatactivity       psql.WhereNullMod[Q, string]
	Lastinspectconditions   psql.WhereNullMod[Q, string]
	Waterorigin             psql.WhereNullMod[Q, enums.FieldseekerPolygonlocationPolygonlocationWateroriginE9018e925F474FF9]
	Filter                  psql.WhereNullMod[Q, string]
	Creationdate            psql.WhereNullMod[Q, time.Time]
	Creator                 psql.WhereNullMod[Q, string]
	Editdate                psql.WhereNullMod[Q, time.Time]
	Editor                  psql.WhereNullMod[Q, string]
	Jurisdiction            psql.WhereNullMod[Q, string]
	ShapeArea               psql.WhereNullMod[Q, float64]
	ShapeLength             psql.WhereNullMod[Q, float64]
	Version                 psql.WhereMod[Q, int32]
}

func (fieldseekerPolygonlocationWhere[Q]) AliasedAs(alias string) fieldseekerPolygonlocationWhere[Q] {
	return buildFieldseekerPolygonlocationWhere[Q](buildFieldseekerPolygonlocationColumns(alias))
}

func buildFieldseekerPolygonlocationWhere[Q psql.Filterable](cols fieldseekerPolygonlocationColumns) fieldseekerPolygonlocationWhere[Q] {
	return fieldseekerPolygonlocationWhere[Q]{
		Objectid:                psql.Where[Q, int64](cols.Objectid),
		Name:                    psql.WhereNull[Q, string](cols.Name),
		Zone:                    psql.WhereNull[Q, string](cols.Zone),
		Habitat:                 psql.WhereNull[Q, enums.FieldseekerPolygonlocationPolygonlocationHabitat45e9dde79ac84d959df8b65](cols.Habitat),
		Priority:                psql.WhereNull[Q, enums.FieldseekerPolygonlocationLocationpriorityEnum](cols.Priority),
		Usetype:                 psql.WhereNull[Q, enums.FieldseekerPolygonlocationPolygonlocationUsetypeE546154cb9544b9aa8e7b13](cols.Usetype),
		Active:                  psql.WhereNull[Q, enums.FieldseekerPolygonlocationNotinuitFEnum](cols.Active),
		Description:             psql.WhereNull[Q, string](cols.Description),
		Accessdesc:              psql.WhereNull[Q, string](cols.Accessdesc),
		Comments:                psql.WhereNull[Q, string](cols.Comments),
		Symbology:               psql.WhereNull[Q, enums.FieldseekerPolygonlocationLocationsymbologyEnum](cols.Symbology),
		Externalid:              psql.WhereNull[Q, string](cols.Externalid),
		Acres:                   psql.WhereNull[Q, float64](cols.Acres),
		Nextactiondatescheduled: psql.WhereNull[Q, time.Time](cols.Nextactiondatescheduled),
		Larvinspectinterval:     psql.WhereNull[Q, int16](cols.Larvinspectinterval),
		Zone2:                   psql.WhereNull[Q, string](cols.Zone2),
		Locationnumber:          psql.WhereNull[Q, int32](cols.Locationnumber),
		Globalid:                psql.WhereNull[Q, uuid.UUID](cols.Globalid),
		Lastinspectdate:         psql.WhereNull[Q, time.Time](cols.Lastinspectdate),
		Lastinspectbreeding:     psql.WhereNull[Q, string](cols.Lastinspectbreeding),
		Lastinspectavglarvae:    psql.WhereNull[Q, float64](cols.Lastinspectavglarvae),
		Lastinspectavgpupae:     psql.WhereNull[Q, float64](cols.Lastinspectavgpupae),
		Lastinspectlstages:      psql.WhereNull[Q, string](cols.Lastinspectlstages),
		Lastinspectactiontaken:  psql.WhereNull[Q, string](cols.Lastinspectactiontaken),
		Lastinspectfieldspecies: psql.WhereNull[Q, string](cols.Lastinspectfieldspecies),
		Lasttreatdate:           psql.WhereNull[Q, time.Time](cols.Lasttreatdate),
		Lasttreatproduct:        psql.WhereNull[Q, string](cols.Lasttreatproduct),
		Lasttreatqty:            psql.WhereNull[Q, float64](cols.Lasttreatqty),
		Lasttreatqtyunit:        psql.WhereNull[Q, string](cols.Lasttreatqtyunit),
		Hectares:                psql.WhereNull[Q, float64](cols.Hectares),
		Lastinspectactivity:     psql.WhereNull[Q, string](cols.Lastinspectactivity),
		Lasttreatactivity:       psql.WhereNull[Q, string](cols.Lasttreatactivity),
		Lastinspectconditions:   psql.WhereNull[Q, string](cols.Lastinspectconditions),
		Waterorigin:             psql.WhereNull[Q, enums.FieldseekerPolygonlocationPolygonlocationWateroriginE9018e925F474FF9](cols.Waterorigin),
		Filter:                  psql.WhereNull[Q, string](cols.Filter),
		Creationdate:            psql.WhereNull[Q, time.Time](cols.Creationdate),
		Creator:                 psql.WhereNull[Q, string](cols.Creator),
		Editdate:                psql.WhereNull[Q, time.Time](cols.Editdate),
		Editor:                  psql.WhereNull[Q, string](cols.Editor),
		Jurisdiction:            psql.WhereNull[Q, string](cols.Jurisdiction),
		ShapeArea:               psql.WhereNull[Q, float64](cols.ShapeArea),
		ShapeLength:             psql.WhereNull[Q, float64](cols.ShapeLength),
		Version:                 psql.Where[Q, int32](cols.Version),
	}
}
