// Code generated by BobGen psql v0.42.5. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var FileuploadErrorCSVS = Table[
	fileuploadErrorCSVColumns,
	fileuploadErrorCSVIndexes,
	fileuploadErrorCSVForeignKeys,
	fileuploadErrorCSVUniques,
	fileuploadErrorCSVChecks,
]{
	Schema: "fileupload",
	Name:   "error_csv",
	Columns: fileuploadErrorCSVColumns{
		Col: column{
			Name:      "col",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CSVFileID: column{
			Name:      "csv_file_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('fileupload.error_csv_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Line: column{
			Name:      "line",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Message: column{
			Name:      "message",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: fileuploadErrorCSVIndexes{
		ErrorCSVPkey: index{
			Type: "btree",
			Name: "error_csv_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "error_csv_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: fileuploadErrorCSVForeignKeys{
		FileuploadErrorCSVErrorCSVCSVFileIDFkey: foreignKey{
			constraint: constraint{
				Name:    "fileupload.error_csv.error_csv_csv_file_id_fkey",
				Columns: []string{"csv_file_id"},
				Comment: "",
			},
			ForeignTable:   "fileupload.csv",
			ForeignColumns: []string{"file_id"},
		},
	},

	Comment: "",
}

type fileuploadErrorCSVColumns struct {
	Col       column
	CSVFileID column
	ID        column
	Line      column
	Message   column
}

func (c fileuploadErrorCSVColumns) AsSlice() []column {
	return []column{
		c.Col, c.CSVFileID, c.ID, c.Line, c.Message,
	}
}

type fileuploadErrorCSVIndexes struct {
	ErrorCSVPkey index
}

func (i fileuploadErrorCSVIndexes) AsSlice() []index {
	return []index{
		i.ErrorCSVPkey,
	}
}

type fileuploadErrorCSVForeignKeys struct {
	FileuploadErrorCSVErrorCSVCSVFileIDFkey foreignKey
}

func (f fileuploadErrorCSVForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FileuploadErrorCSVErrorCSVCSVFileIDFkey,
	}
}

type fileuploadErrorCSVUniques struct{}

func (u fileuploadErrorCSVUniques) AsSlice() []constraint {
	return []constraint{}
}

type fileuploadErrorCSVChecks struct{}

func (c fileuploadErrorCSVChecks) AsSlice() []check {
	return []check{}
}
