// Code generated by BobGen psql v0.42.5. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

var PublicreportOrganizationReportCounts = Table[
	publicreportOrganizationReportCountColumns,
	publicreportOrganizationReportCountIndexes,
	publicreportOrganizationReportCountForeignKeys,
	publicreportOrganizationReportCountUniques,
	publicreportOrganizationReportCountChecks,
]{
	Schema: "publicreport",
	Name:   "organization_report_count",
	Columns: publicreportOrganizationReportCountColumns{
		OrganizationID: column{
			Name:      "organization_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		NuisanceReported: column{
			Name:      "nuisance_reported",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		NuisanceReviewed: column{
			Name:      "nuisance_reviewed",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		NuisanceScheduled: column{
			Name:      "nuisance_scheduled",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		NuisanceTreated: column{
			Name:      "nuisance_treated",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		NuisanceInvalidated: column{
			Name:      "nuisance_invalidated",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		WaterReported: column{
			Name:      "water_reported",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		WaterReviewed: column{
			Name:      "water_reviewed",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		WaterScheduled: column{
			Name:      "water_scheduled",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		WaterTreated: column{
			Name:      "water_treated",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		WaterInvalidated: column{
			Name:      "water_invalidated",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},

	Comment: "",
}

type publicreportOrganizationReportCountColumns struct {
	OrganizationID      column
	NuisanceReported    column
	NuisanceReviewed    column
	NuisanceScheduled   column
	NuisanceTreated     column
	NuisanceInvalidated column
	WaterReported       column
	WaterReviewed       column
	WaterScheduled      column
	WaterTreated        column
	WaterInvalidated    column
}

func (c publicreportOrganizationReportCountColumns) AsSlice() []column {
	return []column{
		c.OrganizationID, c.NuisanceReported, c.NuisanceReviewed, c.NuisanceScheduled, c.NuisanceTreated, c.NuisanceInvalidated, c.WaterReported, c.WaterReviewed, c.WaterScheduled, c.WaterTreated, c.WaterInvalidated,
	}
}

type publicreportOrganizationReportCountIndexes struct{}

func (i publicreportOrganizationReportCountIndexes) AsSlice() []index {
	return []index{}
}

type publicreportOrganizationReportCountForeignKeys struct{}

func (f publicreportOrganizationReportCountForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type publicreportOrganizationReportCountUniques struct{}

func (u publicreportOrganizationReportCountUniques) AsSlice() []constraint {
	return []constraint{}
}

type publicreportOrganizationReportCountChecks struct{}

func (c publicreportOrganizationReportCountChecks) AsSlice() []check {
	return []check{}
}
