// Code generated by BobGen psql v0.42.5. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PublicreportCompliances = Table[
	publicreportComplianceColumns,
	publicreportComplianceIndexes,
	publicreportComplianceForeignKeys,
	publicreportComplianceUniques,
	publicreportComplianceChecks,
]{
	Schema: "publicreport",
	Name:   "compliance",
	Columns: publicreportComplianceColumns{
		AccessInstructions: column{
			Name:      "access_instructions",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AvailabilityNotes: column{
			Name:      "availability_notes",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Comments: column{
			Name:      "comments",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GateCode: column{
			Name:      "gate_code",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		HasDog: column{
			Name:      "has_dog",
			DBType:    "boolean",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		PermissionType: column{
			Name:      "permission_type",
			DBType:    "publicreport.permissionaccess",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReportID: column{
			Name:      "report_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReportPhoneCanText: column{
			Name:      "report_phone_can_text",
			DBType:    "boolean",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		WantsScheduled: column{
			Name:      "wants_scheduled",
			DBType:    "boolean",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Submitted: column{
			Name:      "submitted",
			DBType:    "timestamp without time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: publicreportComplianceIndexes{
		CompliancePkey: index{
			Type: "btree",
			Name: "compliance_pkey",
			Columns: []indexColumn{
				{
					Name:         "report_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "compliance_pkey",
		Columns: []string{"report_id"},
		Comment: "",
	},
	ForeignKeys: publicreportComplianceForeignKeys{
		PublicreportComplianceComplianceReportIDFkey: foreignKey{
			constraint: constraint{
				Name:    "publicreport.compliance.compliance_report_id_fkey",
				Columns: []string{"report_id"},
				Comment: "",
			},
			ForeignTable:   "publicreport.report",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type publicreportComplianceColumns struct {
	AccessInstructions column
	AvailabilityNotes  column
	Comments           column
	GateCode           column
	HasDog             column
	PermissionType     column
	ReportID           column
	ReportPhoneCanText column
	WantsScheduled     column
	Submitted          column
}

func (c publicreportComplianceColumns) AsSlice() []column {
	return []column{
		c.AccessInstructions, c.AvailabilityNotes, c.Comments, c.GateCode, c.HasDog, c.PermissionType, c.ReportID, c.ReportPhoneCanText, c.WantsScheduled, c.Submitted,
	}
}

type publicreportComplianceIndexes struct {
	CompliancePkey index
}

func (i publicreportComplianceIndexes) AsSlice() []index {
	return []index{
		i.CompliancePkey,
	}
}

type publicreportComplianceForeignKeys struct {
	PublicreportComplianceComplianceReportIDFkey foreignKey
}

func (f publicreportComplianceForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.PublicreportComplianceComplianceReportIDFkey,
	}
}

type publicreportComplianceUniques struct{}

func (u publicreportComplianceUniques) AsSlice() []constraint {
	return []constraint{}
}

type publicreportComplianceChecks struct{}

func (c publicreportComplianceChecks) AsSlice() []check {
	return []check{}
}
