// Code generated by BobGen psql v0.0.4-0.20260105020634-53e08d840e47+dirty. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PublicreportPoolPhotos = Table[
	publicreportPoolPhotoColumns,
	publicreportPoolPhotoIndexes,
	publicreportPoolPhotoForeignKeys,
	publicreportPoolPhotoUniques,
	publicreportPoolPhotoChecks,
]{
	Schema: "publicreport",
	Name:   "pool_photo",
	Columns: publicreportPoolPhotoColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('publicreport.pool_photo_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Size: column{
			Name:      "size",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Filename: column{
			Name:      "filename",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PoolID: column{
			Name:      "pool_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UUID: column{
			Name:      "uuid",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: publicreportPoolPhotoIndexes{
		PoolPhotoPkey: index{
			Type: "btree",
			Name: "pool_photo_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "pool_photo_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: publicreportPoolPhotoForeignKeys{
		PublicreportPoolPhotoPoolPhotoPoolIDFkey: foreignKey{
			constraint: constraint{
				Name:    "publicreport.pool_photo.pool_photo_pool_id_fkey",
				Columns: []string{"pool_id"},
				Comment: "",
			},
			ForeignTable:   "publicreport.pool",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type publicreportPoolPhotoColumns struct {
	ID       column
	Size     column
	Filename column
	PoolID   column
	UUID     column
}

func (c publicreportPoolPhotoColumns) AsSlice() []column {
	return []column{
		c.ID, c.Size, c.Filename, c.PoolID, c.UUID,
	}
}

type publicreportPoolPhotoIndexes struct {
	PoolPhotoPkey index
}

func (i publicreportPoolPhotoIndexes) AsSlice() []index {
	return []index{
		i.PoolPhotoPkey,
	}
}

type publicreportPoolPhotoForeignKeys struct {
	PublicreportPoolPhotoPoolPhotoPoolIDFkey foreignKey
}

func (f publicreportPoolPhotoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.PublicreportPoolPhotoPoolPhotoPoolIDFkey,
	}
}

type publicreportPoolPhotoUniques struct{}

func (u publicreportPoolPhotoUniques) AsSlice() []constraint {
	return []constraint{}
}

type publicreportPoolPhotoChecks struct{}

func (c publicreportPoolPhotoChecks) AsSlice() []check {
	return []check{}
}
