-- Code generated by BobGen psql v0.0.4-0.20260105020634-53e08d840e47+dirty. DO NOT EDIT.
-- This file is meant to be re-generated in place and/or deleted at any time.

-- OrgByOauthId
SELECT o.id AS organization_id, o.arcgis_id AS arcgis_id, o.fieldseeker_url AS fieldseeker_url
FROM oauth_token ot
JOIN user_ u ON ot.user_id = u.id
JOIN organization o ON u.organization_id = o.id
WHERE ot.id = $1;
