// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var FieldseekerInspectionsampleErrors = &fieldseekerInspectionsampleErrors{
	ErrUniqueInspectionsamplePkey: &UniqueConstraintError{
		schema:  "fieldseeker",
		table:   "inspectionsample",
		columns: []string{"objectid"},
		s:       "inspectionsample_pkey",
	},
}

type fieldseekerInspectionsampleErrors struct {
	ErrUniqueInspectionsamplePkey *UniqueConstraintError
}
