// Code generated by BobGen psql v0.0.3-0.20251202003046-49148fc66a73+dirty. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var FieldseekerZoneErrors = &fieldseekerZoneErrors{
	ErrUniqueZonesPkey: &UniqueConstraintError{
		schema:  "fieldseeker",
		table:   "zones",
		columns: []string{"objectid", "version"},
		s:       "zones_pkey",
	},
}

type fieldseekerZoneErrors struct {
	ErrUniqueZonesPkey *UniqueConstraintError
}
