// Code generated by BobGen psql v0.0.4-0.20260105020634-53e08d840e47+dirty. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var FieldseekerMosquitoinspectionErrors = &fieldseekerMosquitoinspectionErrors{
	ErrUniqueMosquitoinspectionPkey: &UniqueConstraintError{
		schema:  "fieldseeker",
		table:   "mosquitoinspection",
		columns: []string{"objectid", "version"},
		s:       "mosquitoinspection_pkey",
	},
}

type fieldseekerMosquitoinspectionErrors struct {
	ErrUniqueMosquitoinspectionPkey *UniqueConstraintError
}
